build:
  cuda_version: "12.1.1"
  python_packages:
    - "diffusers==0.33.1"
    - "torch==2.6.0"
    - "hf-transfer==0.1.9"
    - "transformers==4.51.2"
    - "huggingface-hub==0.25.0"
    - "invisible-watermark==0.2.0"
    - "accelerate==1.6.0"
    - "xformers==0.0.29.post3"
    - "sentencepiece==0.2.0"
