build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "diffusers==0.27.0"
    - "torch==2.3.1"
    - "onediff==1.2.0.dev202406120129"
    - "onediffx==1.2.0.dev202406120129"
  run:
    - "python3 -m pip install -U --pre oneflow -f https://github.com/siliconflow/oneflow_releases/releases/expanded_assets/community_cu118"
    
